<?php

$editor = Mage::registry('current_editor');
$associatedProduct = Mage::registry('current_editor_associated_product');

echo "Name : " . $editor->getName() . "<br>";
echo "Address : " . $editor->getAddress() . "<br>";
echo "Phone Number : " . $editor->getPhoneNumber() . "<br>";
echo "Book Type : " . $editor->getBookType() . "<br>";
?>

<br><br>
<div class="block block-related">
    <div class="block-title">
        <h2><?php echo $this->__('Related Products') ?></h2>
</div>
<div class="block-content">
    <ol class="mini-products-list" id="block-related">
        <?php foreach($associatedProduct as $_item): ?>
            <li class="item">
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75) ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                        <?php echo $_item->getDescription() . "<br>"?>
                        <?php echo substr($_item->getPrice(), 0, 4) . " €"?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ol>
</div>
</div>